### ISSUE TITLE
Development

### ISSUE THREAD

**Issue by Adnan1091** [Noswad-Zip/OpenSC#4]
Hello, I've been watching this repo for a long time, but I haven't seen an update for a long time. Is it still under development or you don't want to port it anymore? I have the survivalcraft source code if you want me to share it with you. As I want survivalcraft to be open sourced.

**Comment by Noswad-Zip** [comment]
Currently this is not under development. In the end, the goal was to play survivalcraft worlds in multiplayer and allow for easier modding etc.

You should hang out in our discord server. https://discord.gg/fRcfA8c

**Comment by Noswad-Zip** [comment]
Development resumed. Closing issue.

You can join in conversation in the #opensc channel in the discord server if you like.

**Comment by Adnan1091** [comment]
I don't use discord.If you need source code of this game to speed up the development.Tell me.
